### ISSUE TITLE
CE textimage

### ISSUE THREAD

**Issue by josefglatz** [josefglatz/TYPO3-Distribution#289]
# Problem/Description

Common content element to show
- a text with
- an image (no majority)

# Todo

- [x] TCA
- [x] NCEW
- [x] PageTSConfig
- [x] cropVariants
- [x] RTE preset default
- [x] formDataProvider
- [x] BackendPreview
- [x] FrontendDummy
- [ ] ~valueBadge (which must be implemented first)~
- [x] new columns
- [x] documentation
- [x] backend usability improvements
- [x] TypoScript
