### ISSUE TITLE
CE logo cemetery

### ISSUE THREAD

**Issue by josefglatz** [josefglatz/TYPO3-Distribution#299]
# Need for such a CE
The special need for an own ctype is the problematic that in contrast to a generic image gallery CE such a CE needs special treatments for fal logo image sys_file_reference's for same aspectRatios, imageWhiteSpace, alignments in the parent html element, ...
Also the backend preview deviates strongly from a "normal gallery content element".

# ToDos

- [x] custom IRRE TCA labels
- [x] check in backend preview for all necessary metadata
- [x] use sysFilereference palette tx-theme-image-nolink
- [x] backendpreview error message: "necessary fields are not filled out. Please add content to following fields: <label of fields which are empty strings>
- [ ] ~FE with CSS flexbox selfaligned logos for a nice logo grid (https://codepen.io/drewbots/details/GZYpwY/)~ *moved into FE BS4 project*

**Comment by josefglatz** [comment]
you're right my friend!

such a logo cemetery content element is generically a "normal gallery" – I agree

The special need for an own ctype is the problematic that such CE needs special treatments for fal logo image sys_file_reference's for same aspectRatios, imageWhiteSpace, alignments in the parent html element, ...
Also the backend preview deviates strongly from a "normal gallery content element".

That's the reason why I want to create a ready2use logo-graveyard/-cemetery content element

**Comment by josefglatz** [comment]
# Some screenies of this CE

![image](https://user-images.githubusercontent.com/2861556/38584923-49568d16-3d18-11e8-8a40-8aeddb3c9b28.png)


![image](https://user-images.githubusercontent.com/2861556/38584900-289d45c4-3d18-11e8-9100-7c9c749f682d.png)
